name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/azure-web-app-backend.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: genvolt-webapp-backend
  AZURE_WEBAPP_PACKAGE_PATH: './backend'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Install dependencies and prepare deployment
      run: |
        cd backend
        npm ci
        # Ensure package.json has correct start script
        echo "Preparing deployment package..."

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend'
        runtime-stack: 'NODE|20-lts'